export const SEARCH_FETCH_NEXT_SUCCESS = 'SEARCH_FETCH_NEXT_SUCCESS';
export const SEARCH_FETCH_SUCCESS = 'SEARCH_FETCH_SUCCESS';
export const SEARCH_FETCH_FAILED = 'SEARCH_FETCH_FAILED';
export const FAVORITE_ADD_SUCCESS = 'FAVORITE_ADD_SUCCESS';
export const FAVORITE_REMOVE_SUCCESS = 'FAVORITE_REMOVE_SUCCESS';
export const FAVORITE_FETCH_SUCCESS = 'FAVORITE_FETCH_SUCCESS';
